Tests Alignment
ethereum/eth2-ssv pull request #77
Opened 2021-05-19 14:13 UTC by amir-blox

The following points were handled as part of this task:

1. Test should be structure with subtests:
    - `ibft/pipeline/preprepare/validate_test.go`
    - `ibft/proto/`
2. `ibft/pipeline/changeround` - add unit tests

2021-05-24 12:23 UTC, nivBlox requested changes

2021-05-24 12:23 UTC, nivBlox commented on ibft/pipeline/changeround/validate.go
> +		return fmt.Errorf("change round could not verify signature: %w", err)
lets use errors as we use in the project (stack traces support)

2021-05-25 10:43 UTC, alonmuroch commented
looks good to me

2021-05-25 11:12 UTC, nivBlox approved these changes

2021-05-25 12:30 UTC, lior-blox approved these changes

2021-05-25 12:37 UTC, merged